apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  labels:
    app: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: az4registry.azurecr.io/consumer-image1:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        # volumeMounts:
        # - name: ssl-cert-store
        #   mountPath: "/bitnami/kafka/config/certs"
        #   readOnly: false
      imagePullSecrets:
      - name: acr-secret
      # volumes:
      # - name: ssl-cert-store
      #   configMap:
      #     name: ssl-cert-store
---
apiVersion: v1
kind: Service
metadata:
  name: subscriber
  labels:
    app: subscriber
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: subscriber
  type: LoadBalancer